version: '3'
services:
  db2:
    image: postgres
    ports: 
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  todo:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db2
volumes:
  db_data: